
    menuItem
        -l "Rivet on Selected Face" 
        -c "da_RivetMashFace" 
        -rp "E" 
        -i "MASH_CreateMeshFromPoints.png" 
        menuEditorMenuItem1;

    menuItem
        -l "Constraint Point On Poly" 
        -c "doCreatePointOnPolyConstraintArgList 2 {   \"0\" ,\"0\" ,\"0\" ,\"1\" ,\"\" ,\"1\" ,\"0\" ,\"0\" ,\"0\" ,\"0\" };" 
        -rp "W" 
        -i "pointOnPolyConstraint.png" 
        menuEditorMenuItem2;

setParent -m ..;

