// Hypershade prefs
optionVar
 -iv "HypershadeGridVisibility" 1
 -iv "hyperShadeBringCreatePanelToFront" 1
 -sv "hyperShadeDockingLayout" "000000ff00000000fd00000002000000000000010c00000260fc0200000001fc000000f100000260000000a501000011fa000000000100000002fb00000024004c006f006f006b00640065007600430072006500610074006500500061006e0065006c01000000000000010c000000b500fffffffb00000020004c006f006f006b00640065007600420069006e007300500061006e0065006c0100000000ffffffff0000005600ffffff00000002000002c4000000ebfc0100000003fb00000026004c006f006f006b00640065007600420072006f007700730065007200500061006e0065006c0100000000000002c40000008700fffffffb00000028004c006f006f006b00640065007600500072006f0070006500720074007900500061006e0065006c00000000ad000001bd0000000000000000fb0000002c004c006f006f006b00640065007600530068006100640065007200620061006c006c00500061006e0065006c02000001b000000253000002bc00000190000001b20000026000000004000000020000000800000002fc00000000";

// Paintable Attributes
makePaintable  -at "doubleArray" "membrane" "weightPerVertex";
makePaintable  -at "doubleArray" "nCloth" "tangentialDragPerVertex";
makePaintable  -at "doubleArray" "nCloth" "dragPerVertex";
makePaintable  -at "doubleArray" "nCloth" "liftPerVertex";
makePaintable  -at "doubleArray" "nCloth" "wrinklePerVertex";
makePaintable  -at "doubleArray" "nCloth" "restLengthScalePerVertex";
makePaintable  -at "doubleArray" "nCloth" "inputAttractPerVertex";
makePaintable  -at "doubleArray" "nCloth" "deformPerVertex";
makePaintable  -at "doubleArray" "nCloth" "rigidityPerVertex";
makePaintable  -at "doubleArray" "nCloth" "dampPerVertex";
makePaintable  -at "doubleArray" "nCloth" "restitutionAnglePerVertex";
makePaintable  -at "doubleArray" "nCloth" "bendAngleDropoffPerVertex";
makePaintable  -at "doubleArray" "nCloth" "bendPerVertex";
makePaintable  -at "doubleArray" "nCloth" "compressionPerVertex";
makePaintable  -at "doubleArray" "nCloth" "stretchPerVertex";
makePaintable  -at "doubleArray" "nCloth" "massPerVertex";
makePaintable  -at "doubleArray" "nRigid" "fieldMagnitudePerVertex";
makePaintable  -at "doubleArray" "nRigid" "collideStrengthPerVertex";
makePaintable  -at "doubleArray" "nRigid" "stickinessPerVertex";
makePaintable  -at "doubleArray" "nRigid" "frictionPerVertex";
makePaintable  -at "doubleArray" "nRigid" "bouncePerVertex";
makePaintable  -at "doubleArray" "nRigid" "thicknessPerVertex";
makePaintable  -at "doubleArray" "nCloth" "fieldMagnitudePerVertex";
makePaintable  -at "doubleArray" "nCloth" "collideStrengthPerVertex";
makePaintable  -at "doubleArray" "nCloth" "stickinessPerVertex";
makePaintable  -at "doubleArray" "nCloth" "frictionPerVertex";
makePaintable  -at "doubleArray" "nCloth" "bouncePerVertex";
makePaintable  -at "doubleArray" "nCloth" "thicknessPerVertex";

// Layouts
panelConfiguration -label (localizedPanelLabel("daFourView")) 
	-defaultImage "fourViewLayout.png"
	-image ""
	-sc false
	-configString "paneLayout -e -cn \"quad\" $gMainPane"
	-ap true
		(localizedPanelLabel("Top View")) 
		"modelPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t   modelPanel -mbv $gUseMenusInPanels -unParent -label (localizedPanelLabel(\"Top View\")) -cam `findStartUpCamera top`;}"
		"modelPanel -e -label (localizedPanelLabel(\"Top View\")) -cam `findStartUpCamera top` $panelName"
	-ap true
		(localizedPanelLabel("Persp View")) 
		"modelPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t   modelPanel -mbv $gUseMenusInPanels -unParent -label (localizedPanelLabel(\"Perspective\")) -cam `findStartUpCamera persp`;}"
		"modelPanel -e -label (localizedPanelLabel(\"Persp View\")) -cam `findStartUpCamera persp` $panelName"
	-ap true
		(localizedPanelLabel("Side View")) 
		"modelPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t   modelPanel -mbv $gUseMenusInPanels -unParent -label (localizedPanelLabel(\"Side View\")) -cam `findStartUpCamera side`;}"
		"modelPanel -e -label (localizedPanelLabel(\"Side View\")) -cam `findStartUpCamera side` $panelName"
	-ap true
		(localizedPanelLabel("Front View")) 
		"modelPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t   modelPanel -mbv $gUseMenusInPanels -unParent -label (localizedPanelLabel(\"Front View\")) -cam `findStartUpCamera front`;}"
		"modelPanel -e -label (localizedPanelLabel(\"Front View\")) -cam `findStartUpCamera front` $panelName";

panelConfiguration -label (localizedPanelLabel("daNodeEditor")) 
	-sc false
	-configString "global string $gMainPane; paneLayout -e -cn \"horizontal2\" -ps 1 100 55 -ps 2 100 45 $gMainPane;"
	-ap true
		(localizedPanelLabel("Persp View")) 
		"modelPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t   modelPanel -mbv $gUseMenusInPanels -unParent -label (localizedPanelLabel(\"Persp View\")) -cam `findStartUpCamera persp`;}"
		"modelPanel -edit -label (localizedPanelLabel(\"Persp View\"))  -cam `findStartUpCamera persp` $panelName"
	-ap false
		(localizedPanelLabel("Node Editor")) 
		"scriptedPanel"
		"$panelName = `scriptedPanel -unParent  -type \"nodeEditorPanel\" -l (localizedPanelLabel(\"Node Editor\")) -mbv $menusOkayInPanels `"
		"scriptedPanel -edit -l (localizedPanelLabel(\"Node Editor\")) -mbv $menusOkayInPanels  $panelName";

panelConfiguration -label (localizedPanelLabel("daUvEditor")) 
	-sc false
	-configString "global string $gMainPane; paneLayout -e -cn \"vertical2\" -ps 1 55 100 -ps 2 45 100 $gMainPane;"
	-ap true
		(localizedPanelLabel("Persp View")) 
		"modelPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t   modelPanel -mbv $gUseMenusInPanels -unParent -label (localizedPanelLabel(\"Persp View\")) -cam `findStartUpCamera persp`;}"
		"modelPanel -edit -label (localizedPanelLabel(\"Persp View\"))  -cam `findStartUpCamera persp` $panelName"
	-ap false
		(localizedPanelLabel("UV Editor")) 
		"scriptedPanel"
		"$panelName = `scriptedPanel -unParent  -type \"TextureViewWindow\" -l (localizedPanelLabel(\"UV Editor\")) -mbv $menusOkayInPanels `"
		"scriptedPanel -edit -l (localizedPanelLabel(\"UV Editor\")) -mbv $menusOkayInPanels  $panelName";

panelConfiguration -label (localizedPanelLabel("daGraphEditor")) 
	-defaultImage "perspGraphLayout.png"
	-image ""
	-sc false
	-configString "paneLayout -e -cn \"horizontal2\" -ps 1 100 55 -ps 2 100 45 $gMainPane;"
	-ap true
		(localizedPanelLabel("Persp View")) 
		"modelPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t   modelPanel -mbv $gUseMenusInPanels -unParent -label (localizedPanelLabel(\"Persp View\")) -cam `findStartUpCamera persp`;}"
		"modelPanel -edit -label (localizedPanelLabel(\"Persp View\"))  -cam `findStartUpCamera persp` $panelName"
	-ap false
		(localizedPanelLabel("Graph Editor")) 
		"scriptedPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t  scriptedPanel -mbv $gUseMenusInPanels -type graphEditor -unParent -label (localizedPanelLabel(\"Graph Editor\"));}"
		"scriptedPanel -edit -label (localizedPanelLabel(\"Graph Editor\"))  $panelName";

panelConfiguration -label (localizedPanelLabel("daShapeEditor")) 
	-defaultImage "vacantCell.png"
	-image ""
	-sc false
	-configString "paneLayout -e -cn \"horizontal2\" -ps 1 100 55 -ps 2 100 45 $gMainPane;"
	-ap true
		(localizedPanelLabel("Persp View")) 
		"modelPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t   modelPanel -mbv $gUseMenusInPanels -unParent -label (localizedPanelLabel(\"Persp View\")) -cam `findStartUpCamera persp`;}"
		"modelPanel -edit -label (localizedPanelLabel(\"Persp View\"))  -cam `findStartUpCamera persp` $panelName"
	-ap false
		(localizedPanelLabel("Shape Editor")) 
		"shapePanel"
		"shapePanel -unParent -l (localizedPanelLabel(\"Shape Editor\")) -mbv $menusOkayInPanels "
		"shapePanel -edit -l (localizedPanelLabel(\"Shape Editor\")) -mbv $menusOkayInPanels  $panelName";

panelConfiguration -label (localizedPanelLabel("daPoseEditor")) 
	-defaultImage "vacantCell.png"
	-image ""
	-sc false
	-configString "global string $gMainPane; paneLayout -e -cn \"horizontal2\" -ps 1 100 55 -ps 2 100 45 $gMainPane;"
	-ap true
		(localizedPanelLabel("Persp View")) 
		"modelPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t   modelPanel -mbv $gUseMenusInPanels -unParent -label (localizedPanelLabel(\"Persp View\")) -cam `findStartUpCamera persp`;}"
		"modelPanel -edit -label (localizedPanelLabel(\"Persp View\"))  -cam `findStartUpCamera persp` $panelName"
	-ap false
		(localizedPanelLabel("Pose Editor")) 
		"posePanel"
		"posePanel -unParent -l (localizedPanelLabel(\"Pose Editor\")) -mbv $menusOkayInPanels "
		"posePanel -edit -l (localizedPanelLabel(\"Pose Editor\")) -mbv $menusOkayInPanels  $panelName";

panelConfiguration -label (localizedPanelLabel("daComponentEditor")) 
	-defaultImage "vacantCell.png"
	-image ""
	-sc false
	-configString "global string $gMainPane; paneLayout -e -cn \"horizontal2\" -ps 1 100 55 -ps 2 100 45 $gMainPane;"
	-ap true
		(localizedPanelLabel("Persp View")) 
		"modelPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t   modelPanel -mbv $gUseMenusInPanels -unParent -label (localizedPanelLabel(\"Persp View\")) -cam `findStartUpCamera persp`;}"
		"modelPanel -edit -label (localizedPanelLabel(\"Persp View\"))  -cam `findStartUpCamera persp` $panelName"
	-ap false
		(localizedPanelLabel("Component Editor")) 
		"scriptedPanel"
		"$panelName = `scriptedPanel -unParent  -type \"componentEditorPanel\" -l (localizedPanelLabel(\"Component Editor\")) -mbv $menusOkayInPanels `"
		"scriptedPanel -edit -l (localizedPanelLabel(\"Component Editor\")) -mbv $menusOkayInPanels  $panelName";

panelConfiguration -label (localizedPanelLabel("daRelationshipEditor")) 
	-defaultImage "perspRelationshipEditorLayout.png"
	-image ""
	-sc false
	-configString "paneLayout -e -cn \"horizontal2\" -ps 1 100 55 -ps 2 100 45 $gMainPane;"
	-ap true
		(localizedPanelLabel("Persp View")) 
		"modelPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t   modelPanel -mbv $gUseMenusInPanels -unParent -label (localizedPanelLabel(\"Persp View\")) -cam `findStartUpCamera persp`;}"
		"modelPanel -edit -label (localizedPanelLabel(\"Persp View\"))  -cam `findStartUpCamera persp` $panelName"
	-ap false
		(localizedPanelLabel("Relationship Editor")) 
		"scriptedPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t  scriptedPanel -mbv $gUseMenusInPanels -type relationshipPanel -unParent -label (localizedPanelLabel(\"Relationship Editor\"));}"
		"scriptedPanel -edit -label (localizedPanelLabel(\"Relationship Editor\"))  $panelName";

panelConfiguration -label (localizedPanelLabel("daDynamicRelationshipEditor")) 
	-defaultImage "perspRelationshipEditorLayout.png"
	-image ""
	-sc false
	-configString "paneLayout -e -cn \"horizontal2\" -ps 1 100 55 -ps 2 100 45 $gMainPane;"
	-ap true
		(localizedPanelLabel("Persp View")) 
		"modelPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t   modelPanel -mbv $gUseMenusInPanels -unParent -label (localizedPanelLabel(\"Persp View\")) -cam `findStartUpCamera persp`;}"
		"modelPanel -edit -label (localizedPanelLabel(\"Persp View\"))  -cam `findStartUpCamera persp` $panelName"
	-ap false
		(localizedPanelLabel("Dynamic Relationship Editor")) 
		"scriptedPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t  scriptedPanel -mbv $gUseMenusInPanels -type dynRelEdPanel -unParent -label (localizedPanelLabel(\"Dynamic Relationship Editor\"));}"
		"scriptedPanel -edit -label (localizedPanelLabel(\"Dynamic Relationship Editor\"))  $panelName";

panelConfiguration -label (localizedPanelLabel("daReferenceEditor")) 
	-defaultImage "vacantCell.png"
	-image ""
	-sc false
	-configString "global string $gMainPane; paneLayout -e -cn \"horizontal2\" -ps 1 100 55 -ps 2 100 45 $gMainPane;"
	-ap true
		(localizedPanelLabel("Persp View")) 
		"modelPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t   modelPanel -mbv $gUseMenusInPanels -unParent -label (localizedPanelLabel(\"Persp View\")) -cam `findStartUpCamera persp`;}"
		"modelPanel -edit -label (localizedPanelLabel(\"Persp View\"))  -cam `findStartUpCamera persp` $panelName"
	-ap false
		(localizedPanelLabel("Reference Editor")) 
		"scriptedPanel"
		"$panelName = `scriptedPanel -unParent  -type \"referenceEditorPanel\" -l (localizedPanelLabel(\"Reference Editor\")) -mbv $menusOkayInPanels `"
		"scriptedPanel -edit -l (localizedPanelLabel(\"Reference Editor\")) -mbv $menusOkayInPanels  $panelName";

panelConfiguration -label (localizedPanelLabel("daHyperShade")) 
	-defaultImage "vacantCell.png"
	-image ""
	-sc false
	-configString "global string $gMainPane; paneLayout -e -cn \"vertical2\" -ps 1 55 100 -ps 2 45 100 $gMainPane;"
	-ap true
		(localizedPanelLabel("Persp View")) 
		"modelPanel"
		"{global int $gUseMenusInPanels;\t\t\t\t   modelPanel -mbv $gUseMenusInPanels -unParent -label (localizedPanelLabel(\"Persp View\")) -cam `findStartUpCamera persp`;}"
		"modelPanel -edit -label (localizedPanelLabel(\"Persp View\"))  -cam `findStartUpCamera persp` $panelName"
	-ap false
		(localizedPanelLabel("Hypershade")) 
		"scriptedPanel"
		"$panelName = `scriptedPanel -unParent  -type \"hyperShadePanel\" -l (localizedPanelLabel(\"Hypershade\")) -mbv $menusOkayInPanels `"
		"scriptedPanel -edit -l (localizedPanelLabel(\"Hypershade\")) -mbv $menusOkayInPanels  $panelName";