
    menuItem
        -label "Insert Knot" 
        -command "InsertKnot;" 
        -radialPosition "N" 
        -image "insertKnot.png" 
        -sourceType "mel" 
        menuEditorMenuItem1;

    menuItem
        -label "Detach Curve" 
        -command "DetachCurve;" 
        -radialPosition "S" 
        -image "detachCurve.png" 
        -sourceType "mel" 
        menuEditorMenuItem2;

setParent -m ..;

