
    menuItem
        -label "Make Collide" 
        -command "makeCollidePaintEffects;" 
        -radialPosition "N" 
        -image "hairCollide.png" 
        -sourceType "mel" 
        menuEditorMenuItem1;

    menuItem
        -label "Create Modifier" 
        -command "createLineModifier;" 
        -radialPosition "S" 
        -image "toonLineModifier.png" 
        -sourceType "mel" 
        menuEditorMenuItem3;

setParent -m ..;

