
    menuItem
        -label "Project Curve on Surface" 
        -command "ProjectCurveOnSurface" 
        -radialPosition "N" 
        -image "projectCurve.png" 
        -sourceType "mel" 
        menuEditorMenuItem3;

    menuItem
        -label "menuEditorMenuItem4" 
        -command "ProjectCurveOnSurfaceOptions" 
        -optionBox 1
        -sourceType "mel" 
        menuEditorMenuItem4;

setParent -m ..;

