
    menuItem
        -label "Edit Shader" 
        -command "da_AiStandardVolume" 
        -radialPosition "E" 
        -image "VolumeShelf.png" 
        -sourceType "mel" 
        menuEditorMenuItem1;

    menuItem
        -label "Edit Volume" 
        -command "da_AiVolumeShape" 
        -radialPosition "W" 
        -image "WireFrameOnShaded.png" 
        -sourceType "mel" 
        menuEditorMenuItem2;

setParent -m ..;

