
    menuItem
        -label "Transform nConstraint" 
        -command "performCreateDynamicConstraint 0 \"transform\";" 
        -radialPosition "N" 
        -image "nConstraintTransform.png" 
        -sourceType "mel" 
        menuEditorMenuItem1;

    menuItem
        -command "performCreateDynamicConstraint 1 \"transform\";" 
        -optionBox 1
        -sourceType "mel" 
        menuEditorMenuItem2;

setParent -m ..;

