
    menuItem
        -label "Booleans" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "W" 
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -image "polyBooleansIntersection.png" 
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem2;

        menuItem
            -label "Union" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "da_interactiveUnion" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NW" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyBooleansUnion.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem1;

        menuItem
            -label "Difference" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "da_interactiveDifference" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "W" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyBooleansDifference.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "Intersection" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "da_interactiveIntersection" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SW" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyBooleansIntersection.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

    setParent -m ..;

    menuItem
        -label "Combine" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "CombinePolygons;" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "NE" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "polyUnite.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem3;

    menuItem
        -label "menuEditorMenuItem4" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "CombinePolygonsOptions;" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 1
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem4;

    menuItem
        -label "Smooth" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "SmoothPolygon" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "S" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "polySmooth.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem17;

    menuItem
        -label "menuEditorMenuItem22" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "SmoothPolygonOptions;" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 1
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem22;

    menuItem
        -label "Brushes" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "N" 
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -image "out_brush.png" 
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem32;

        menuItem
            -label "Paint Hair Follicle" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "paintHairTool 0;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "E" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "hairPaint.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem4;

        menuItem
            -label "menuEditorMenuItem5" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "paintHairTool 1;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

        menuItem
            -label "Paint Skin Weights" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "ArtPaintSkinWeightsToolOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NW" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "paintSkinWeights.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem6;

        menuItem
            -label "Paint Attributes" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "ArtPaintAttrToolOptions;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SE" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "artAttr.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem7;

        menuItem
            -label "3D Paint Tool" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "Art3dPaintToolOptions;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "NE" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "art3dPaint.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem8;

        menuItem
            -label "3D UV Grab" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "layoutPerspUV;\nShowMeshGrabUVToolOptions;\ntextureWindow -edit -displaySolidMap 0 polyTexturePlacementPanel1;\ntextureWindow -edit -displayDistortion 0 polyTexturePlacementPanel1;\ntextureWindow -edit -displayCheckered 1 polyTexturePlacementPanel1;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "SW" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "UV_3D_Grab_Brush.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem9;

        menuItem
            -label "Paint Effects" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "PaintOnPaintableObjects;\nMakePaintable;\nPaintEffectsTool;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "W" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "paintEffectsTool.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

        menuItem
            -label "menuEditorMenuItem3" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "PaintOnPaintableObjects;\nMakePaintable;\n{VisorWindow;string $pnl=visorPanelName();if(size($pnl)>0) visorPanelMenuCommand( $pnl, \"selectOrCreateTabByLabel Paint Effects\");};" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "Sculpt Geometry" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "SetMeshSculptTool" 
            -keyEquivalent "1" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 1
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "N" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "Sculpt.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem10;

        menuItem
            -label "menuEditorMenuItem11" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "ShowMeshSculptToolOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem11;

    setParent -m ..;

    menuItem
        -label "Add Divisions" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "performPolySubdivide \"\" 0" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "SW" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "polySubdFacet.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem11;

    menuItem
        -label "menuEditorMenuItem25" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "SubdividePolygonOptions" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 1
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem25;

    menuItem
        -label "Trans Attr" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "performTransferAttributes 0" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "SE" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "polyTransferAttributes.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem13;

    menuItem
        -label "menuEditorMenuItem16" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "performTransferAttributes 1" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 1
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem16;

    menuItem
        -label "Bevel" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "BevelPolygon;" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "NW" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "polyBevel.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem18;

    menuItem
        -label "menuEditorMenuItem19" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "BevelPolygonOptions;" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 1
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem7;

    menuItem
        -label "Extrude" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "PolyExtrude" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "E" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "polyExtrudeFacet.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem24;

    menuItem
        -label "menuEditorMenuItem27" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "PolyExtrudeOptions" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 1
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem12;

    menuItem
        -label "Modeling Toolkit" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "showModelingToolkit" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "modelToolkit.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem10;

    menuItem
        -label "Toggle Border Edges" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "ToggleBorderEdges" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "borderEdge.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem26;

    menuItem
        -label "Mirror Geometries" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "MirrorPolygonGeometry;" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "polyMirrorGeometry.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem33;

    menuItem
        -label "menuEditorMenuItem34" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "MirrorPolygonGeometryOptions;" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 1
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 0
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem14;

    menuItem
        -label "Voxelize Mesh" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "mashVoxelizer" 
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "ae_MASH_Explode.png" 
        -echoCommand 0
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem9;

    menuItem
        -label "separator" 
        -divider 1
        -dividerLabel "separator" 
        -subMenu 0
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem23;

    menuItem
        -label "Subdivision" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -image "subdivPolyMode.png" 
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem6;

        menuItem
            -label "Adaptive OpenSubdiv" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem9;

            menuItem
                -label "On" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "OpenSubdAdapt" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Off" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "OpenSubdNoAdapt" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

        setParent -m ..;

        menuItem
            -label "Viewport Displace" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem11;

            menuItem
                -label "On" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "OpenSubdDisplace" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Off" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "OpenSubdNoDisplace" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

        setParent -m ..;

        menuItem
            -label "OpenCL" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem10;

            menuItem
                -label "On" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "OpenSubdCL" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Off" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "OpenSubdNoCL" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

        setParent -m ..;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

        menuItem
            -label "Poly to Legacy Subdiv" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "doSubdivCreate( \"2\", { \"1\",\"1\",\"1000\",\"32\"} )" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyToSubdivs.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem8;

        menuItem
            -label "menuEditorMenuItem9" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateSubdivSurfaceOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem7;

        menuItem
            -label "Subdiv to Poly" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreatePolyFromPreview" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "subdivCreate.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem6;

    setParent -m ..;

    menuItem
        -label "Deformers" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -image "menuIconDeformations.png" 
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem20;

        menuItem
            -label "Edit Relationship" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem19;

            menuItem
                -label "Deformer Set Editor" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "DeformerSetEditor" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "menuIconWindow.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Set Membership" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "PaintSetMembershipToolOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "paintSetMembership.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Edit Membership Tool" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "EditMembershipTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "setEdit.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

        setParent -m ..;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem23;

        menuItem
            -label "Blend Shape" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -image "blendShape.png" 
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem26;

            menuItem
                -label "Create Blend Shape" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "CreateBlendShape;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "blendShape.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "menuEditorMenuItem3" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "CreateBlendShapeOptions;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Add Shape" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "AddBlendShape;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "blendShapePlus.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

            menuItem
                -label "menuEditorMenuItem6" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "AddBlendShapeOptions;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

        setParent -m ..;

        menuItem
            -label "Nonlinear" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -image "menuIconDeformations.png" 
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem18;

            menuItem
                -label "Bend" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "Bend;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "bendNLD.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "menuEditorMenuItem2" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "BendOptions;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem13;

            menuItem
                -label "Flare" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "Flare;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "flareNLD.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "menuEditorMenuItem4" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "FlareOptions;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem14;

            menuItem
                -label "Sine" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "Sine" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "sineNLD.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

            menuItem
                -label "menuEditorMenuItem6" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SineOptions;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem15;

            menuItem
                -label "Squash" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "Squash" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "squashNLD.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem7;

            menuItem
                -label "menuEditorMenuItem8" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "SquashOptions;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem16;

            menuItem
                -label "Twist" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "Twist" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "twistNLD.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem9;

            menuItem
                -label "menuEditorMenuItem10" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "TwistOptions" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem17;

            menuItem
                -label "Wave" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "Wave" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "waveNLD.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem11;

            menuItem
                -label "menuEditorMenuItem12" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "WaveOptions;" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem18;

        setParent -m ..;

        menuItem
            -label "Cluster" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateCluster" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "cluster.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem22;

        menuItem
            -label "menuEditorMenuItem24" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateClusterOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem9;

        menuItem
            -label "Delta Mush" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "DeltaMush" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem14;

        menuItem
            -label "menuEditorMenuItem17" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "DeltaMushOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem25;

        menuItem
            -label "Membrane" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "createMembrane" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

        menuItem
            -label "Lattice" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateLattice" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "lattice.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "menuEditorMenuItem8" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateLatticeOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem27;

        menuItem
            -label "Wrap" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateWrap;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "wrap.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem10;

        menuItem
            -label "menuEditorMenuItem11" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateWrapOptions;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem28;

        menuItem
            -label "ShrinkWrap" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateShrinkWrap;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "shrinkwrap.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem12;

        menuItem
            -label "menuEditorMenuItem13" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateShrinkWrapOptions;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem29;

        menuItem
            -label "UV Based" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "DeformerUV" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyUnfoldUVs.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem16;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem8;

        menuItem
            -label "Add Influence to Skin" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "AddInfluence" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "addWrapInfluence.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem11;

        menuItem
            -label "menuEditorMenuItem13" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "AddInfluenceOptions;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem30;

        menuItem
            -label "Remove Influence to Skin" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "RemoveInfluence;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "removeWrapInfluence.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem15;

        menuItem
            -label "Copy Skin Weights" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CopySkinWeights" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "copySkinWeight.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem21;

        menuItem
            -label "menuEditorMenuItem24" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CopySkinWeightsOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem31;

        menuItem
            -label "Unbind Skin" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "DetachSkin" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "detachSkin.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem17;

        menuItem
            -label "menuEditorMenuItem20" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "DetachSkinOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem32;

    setParent -m ..;

    menuItem
        -label "UV Mapping" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -image "polyUnfoldUVs.png" 
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem8;

        menuItem
            -label "Select UVs" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "SelectUV" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "N" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polySelectUV.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem1;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

        menuItem
            -label "Automatic" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "performPolyAutoProj 0;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyAutoProj.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "menuEditorMenuItem4" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "performPolyAutoProj 1;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem4;

        menuItem
            -label "Planar" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "performPolyProjectionArgList \"1\" {\"0\", \"Planar\", \"ls -selection\", \"0\"} \"\";" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyPlanProj.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

        menuItem
            -label "menuEditorMenuItem6" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "performPolyProjectionArgList \"1\" {\"1\", \"Planar\", \"ls -selection\", \"0\"} \"\";" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem6;

        menuItem
            -label "Cylindrical" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "performPolyProjectionArgList \"1\" {\"0\", \"Cylindrical\", \"ls -selection\", \"0\"} \"\";" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyCylProj.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem7;

        menuItem
            -label "menuEditorMenuItem8" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "performPolyProjectionArgList \"1\" {\"1\", \"Cylindrical\", \"ls -selection\", \"0\"} \"\";" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem8;

        menuItem
            -label "Spherical" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "performPolyProjectionArgList \"1\" {\"0\", \"Spherical\", \"ls -selection\", \"0\"} \"\";" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polySphereProj.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem9;

        menuItem
            -label "menuEditorMenuItem10" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "performPolyProjectionArgList \"1\" {\"1\", \"Planar\", \"ls -selection\", \"0\"} \"\";" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem10;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem11;

        menuItem
            -label "UV Borders" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "int $borders[] = `polyOptions -q -displayMapBorder`;float $borderWidth[] = `optionVar -q displayPolyBorderEdgeSize`;polyOptions -displayMapBorder (!$borders[0]) -sizeBorder $borderWidth[1];" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "textureBorder.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem12;

    setParent -m ..;

    menuItem
        -label "Normals" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -image "polyNormalsPropagate.png" 
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem15;

        menuItem
            -label "Conform" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "ConformPolygonNormals;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyNormalsConform.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem1;

        menuItem
            -label "Reverse" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "ReversePolygonNormals" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyNormal.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

        menuItem
            -label "Unlock" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "polyNormalPerVertex -ufn true;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyNormalUnlock.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem4;

        menuItem
            -label "Set Soften Edge" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "SoftPolyEdgeElements 1" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polySoftEdge.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

        menuItem
            -label "menuEditorMenuItem8" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "polySoftEdgeWin" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem6;

        menuItem
            -label "Set Harden Edge" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "SoftPolyEdgeElements 0;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyHardEdge.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem7;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem12;

        menuItem
            -label "Double Side On" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "DoubleSideOn" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "polyToggleProxy.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem13;

        menuItem
            -label "Double Side Off" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "DoubleSideOff" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "da_polyToggleProxy.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem14;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem9;

        menuItem
            -label "Toggle Display" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "ToggleFaceNormalDisplay;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "da_show.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem10;

        menuItem
            -label "Change Size" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "setPolygonDisplaySettings(\"normalSize\");" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "resizeWindow.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem11;

    setParent -m ..;

    menuItem
        -label "Shading" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -image "render_adskMaterial.png" 
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem5;

        menuItem
            -label "Assign New Material" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "createAssignNewMaterialTreeLister \"\";" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -radialPosition "N" 
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "render_adskMaterial.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem1;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

        menuItem
            -label "Shaded Brightness Two Tone" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "assignToonShader \"shadedBrightness\"" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "toonBrightness2.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "Shaded Brightness Three Tone" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "assignToonShader \"threeToneBrightness\"" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "toonBrightness3.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem4;

        menuItem
            -label "Circle Highlight" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "assignToonShader \"circleHighlight\"" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "toonCircleHigh.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem8;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

        menuItem
            -label "Add Toon Outline" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "assignNewPfxToon" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "toonAddOutline.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem6;

        menuItem
            -label "Remove Toon Outlines" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "removePfxToonOutlines" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "toonRemoveOutline.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem7;

    setParent -m ..;

    menuItem
        -label "Dynamics" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -image "out_nucleus.png" 
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem21;

        menuItem
            -label "Dynamic Relationships" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "DynamicRelationshipEditor" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "menuIconWindow.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem44;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem26;

        menuItem
            -label "Create nCloth" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "nClothCreate" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "nClothCreate.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "menuEditorMenuItem8" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "nClothCreateOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem4;

        menuItem
            -label "Create Passive Collider" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "nClothMakeCollide" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "nClothCreatePassive.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

        menuItem
            -label "menuEditorMenuItem9" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "nClothMakeCollideOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem6;

        menuItem
            -label "Set Initial State" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "setNClothStartState;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "hairStartFromCurrent.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem1;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem24;

        menuItem
            -label "Emit Particle" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "NEmitFromObject" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "emitter.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem18;

        menuItem
            -label "menuEditorMenuItem25" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "NEmitFromObjectOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem9;

        menuItem
            -label "Fill Object With Particle" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "ParticleFill" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "nPartfillObject.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem20;

        menuItem
            -label "menuEditorMenuItem26" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "ParticleFillOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem10;

        menuItem
            -label "Particle Style" 
			-image "out_particle.png" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem38;

            menuItem
                -label "Points" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "optionVar -stringValue NParticleStyle \"Points\";" 
				-image "nPartPoints.png"
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -radialPosition "N" 
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Balls" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "optionVar -stringValue NParticleStyle \"Balls\";" 
				-image "nPartBalls.png"
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Cloud" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "optionVar -stringValue NParticleStyle \"Cloud\";" 
				-image "nPartCloud.png"
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "ThickCloud" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "optionVar -stringValue NParticleStyle \"ThickCloud\";" 
				-image "nPartThickCloud.png"
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "Water" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "optionVar -stringValue NParticleStyle \"Water\";" 
				-image "nPartWater.png"
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

        setParent -m ..;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem27;

        menuItem
            -label "Create Hair" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateHair" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "hairCreate.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem22;

        menuItem
            -label "menuEditorMenuItem29" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateHairOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem13;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem11;

        menuItem
            -label "Create Active Rigid Body" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateActiveRigidBody" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "rigid.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem12;

        menuItem
            -label "menuEditorMenuItem13" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateActiveRigidBodyOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem15;

        menuItem
            -label "Create Passive Rigid Body" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreatePassiveRigidBody" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "rigidPassive.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem14;

        menuItem
            -label "menuEditorMenuItem15" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreatePassiveRigidBodyOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem16;

        menuItem
            -label "Add Fields" 
			-image "posRadial.png" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem28;

            menuItem
                -label "Air" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "dynExecuteFieldCommands 1 \"air -pos 0 0 0 -m 4 -att 1 -dx 0 -dy 1 -dz 0 -s 5 -iv 1 -iro 1 -vco 0 -es 0  -mxd 20  -vsh none -vex 0 -vof 0 0 0 -vsw 360 -tsr 0.5 \"" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "posAir.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Drag" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "dynExecuteFieldCommands 1 \"drag -pos 0 0 0 -m 0.05 -att 1 -dx 0 -dy 0 -dz 0 -ud 0  -mxd -1  -vsh none -vex 0 -vof 0 0 0 -vsw 360 -tsr 0.5 \"" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "posDrag.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Gravity" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "dynExecuteFieldCommands 1 \"gravity -pos 0 0 0 -m 9.8 -att 0 -dx 0 -dy -1 -dz 0  -mxd -1  -vsh none -vex 0 -vof 0 0 0 -vsw 360 -tsr 0.5 \"" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "posGravity.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "Newton" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "dynExecuteFieldCommands 1 \"newton -pos 0 0 0 -m 5 -att 1 -mnd 0.2  -mxd -1  -vsh none -vex 0 -vof 0 0 0 -vsw 360 -tsr 0.5 \"" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "posNewton.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "Radial" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "dynExecuteFieldCommands 1 \"radial -pos 0 0 0 -m 5 -att 1 -typ 0  -mxd 20  -vsh none -vex 0 -vof 0 0 0 -vsw 360 -tsr 0.5 \"" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "posRadial.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

            menuItem
                -label "Turbulence" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "dynExecuteFieldCommands 1 \"turbulence -pos 0 0 0 -m 5 -att 1 -f 1 -phaseX 0 -phaseY 0 -phaseZ 0 -noiseLevel 0 -noiseRatio 0.707  -mxd -1  -vsh none -vex 0 -vof 0 0 0 -vsw 360 -tsr 0.5 \"" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "posTurbulence.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem6;

            menuItem
                -label "Uniform" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "dynExecuteFieldCommands 1 \"uniform -pos 0 0 0 -m 5 -att 1 -dx 1 -dy 0 -dz 0  -mxd -1  -vsh none -vex 0 -vof 0 0 0 -vsw 360 -tsr 0.5 \"" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "posUniform.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem7;

            menuItem
                -label "Vortex" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "dynExecuteFieldCommands 1 \"vortex -pos 0 0 0 -m 5 -att 1 -ax 0 -ay 1 -az 0  -mxd -1  -vsh none -vex 0 -vof 0 0 0 -vsw 360 -tsr 0.5 \"" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "posVortex.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem8;

            menuItem
                -label "separator" 
                -divider 1
                -dividerLabel "separator" 
                -subMenu 0
                -tearOff 0
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem9;

            menuItem
                -label "Volume Axis" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "dynExecuteFieldCommands 1 \"volumeAxis -pos 0 0 0 -m 5 -att 0 -ia 0 -afc 1 -afx 1 -arx 0 -alx 0 -drs 0 -dx 1 -dy 0 -dz 0 -trb 0 -trs 0.2 -tfx 1 -tfy 1 -tfz 1 -tox 0 -toy 0 -toz 0 -dtr 0  -mxd -1  -vsh cube -vof 0 0 0 -vsw 360 -tsr 0.5 \"" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "posVolumeAxis.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem10;

        setParent -m ..;

        menuItem
            -label "Constrain" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem41;

            menuItem
                -label "Nail" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "constrain -nail " 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "constraint.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

            menuItem
                -label "Pin" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "constrain -pin -i 0 " 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "constraint.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "Hinge" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "constrain -hinge -o 0 0 0 " 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "constraint.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Spring" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "constrain -spring -st 5 -d 0.1 " 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "constraint.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "Barrier" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "constrain -barrier -o 0 0 0 " 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "constraint.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

        setParent -m ..;

        menuItem
            -label "Set Initial State" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "setDynStartState;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem40;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem34;

        menuItem
            -label "Emit Fluid From Object" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "EmitFluidFromObject" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "fluidObjectEmit.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem35;

        menuItem
            -label "menuEditorMenuItem36" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "EmitFluidFromObjectOptions" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem17;

        menuItem
            -label "Make Fluid Collide" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "MakeFluidCollide" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "fluidCollide.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem37;

        menuItem
            -label "menuEditorMenuItem39" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "MakeFluidCollideOptions;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem19;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

        menuItem
            -label "Create Bifrost Liquid" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateBifrostLiquid;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "out_bifrostShape.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem7;

        menuItem
            -label "Create Bifrost Aero" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "CreateBifrostAero" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "out_bifrostShape.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem8;

    setParent -m ..;

    menuItem
        -label "XGen" 
        -divider 0
        -subMenu 1
        -tearOff 0
        -altModifier 0
        -optionModifier 0
        -commandModifier 0
        -ctrlModifier 0
        -shiftModifier 0
        -optionBox 0
        -enable 1
        -data 0
        -allowOptionBoxes 1
        -enableCommandRepeat 1
        -image "xgDEditor.png" 
        -italicized 0
        -boldFont 1
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem28;

        menuItem
            -label "Create Interactive Groom" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "XgmCreateInteractiveGroomSplines" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "xgIG_creation.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem9;

        menuItem
            -label "menuEditorMenuItem13" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "XgmCreateInteractiveGroomSplinesOption" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem7;

        menuItem
            -label "Interactive Brush" 
            -divider 0
            -subMenu 1
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -enableCommandRepeat 1
            -image "xgIG_density_24.png" 
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem11;

            menuItem
                -label "Density" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetDensityBrushTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "xgIG_density.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem1;

            menuItem
                -label "menuEditorMenuItem2" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetDensityBrushToolOption" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem2;

            menuItem
                -label "Place" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetPlaceBrushTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "xgIG_place.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem5;

            menuItem
                -label "menuEditorMenuItem3" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetPlaceBrushToolOption" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem3;

            menuItem
                -label "Length" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetLengthBrushTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "xgIG_length.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem7;

            menuItem
                -label "menuEditorMenuItem4" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetLengthBrushToolOption" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem4;

            menuItem
                -label "Cut" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetCutBrushTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "xgIG_cut.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem9;

            menuItem
                -label "menuEditorMenuItem6" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetCutBrushToolOption" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem6;

            menuItem
                -label "Width" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetWidthBrushTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "xgIG_width.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem11;

            menuItem
                -label "menuEditorMenuItem8" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetWidthBrushToolOption" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem8;

            menuItem
                -label "Comb" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetCombBrushTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "xgIG_comb.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem13;

            menuItem
                -label "menuEditorMenuItem10" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetCombBrushToolOption" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem10;

            menuItem
                -label "Grab" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetGrabBrushTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "xgIG_grab.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem15;

            menuItem
                -label "menuEditorMenuItem12" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetGrabBrushToolOption" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem12;

            menuItem
                -label "Smooth" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetSmoothBrushTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "xgIG_smooth.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem17;

            menuItem
                -label "menuEditorMenuItem14" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetSmoothBrushToolOption" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem14;

            menuItem
                -label "Noise" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetNoiseBrushTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "xgIG_noise.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem19;

            menuItem
                -label "menuEditorMenuItem16" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetNoiseBrushToolOption" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem16;

            menuItem
                -label "Clump" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetClumpBrushTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "xgIG_clump.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem21;

            menuItem
                -label "menuEditorMenuItem18" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetClumpBrushToolOption" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem18;

            menuItem
                -label "Part" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetPartBrushTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "xgIG_part.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem23;

            menuItem
                -label "menuEditorMenuItem20" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetPartBrushToolOption" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem20;

            menuItem
                -label "separator" 
                -divider 1
                -dividerLabel "separator" 
                -subMenu 0
                -tearOff 0
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem26;

            menuItem
                -label "Freeze" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetFreezeBrushTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "xgIG_freeze.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem25;

            menuItem
                -label "menuEditorMenuItem22" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetFreezeBrushToolOption" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem22;

            menuItem
                -label "Select" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetSelectBrushTool" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 0
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 1
                -image "xgIG_select.png" 
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem27;

            menuItem
                -label "menuEditorMenuItem24" 
                -divider 0
                -subMenu 0
                -tearOff 0
                -command "XgmSetSelectBrushToolOption" 
                -altModifier 0
                -optionModifier 0
                -commandModifier 0
                -ctrlModifier 0
                -shiftModifier 0
                -optionBox 1
                -enable 1
                -data 0
                -allowOptionBoxes 1
                -postMenuCommandOnce 0
                -enableCommandRepeat 0
                -echoCommand 0
                -italicized 0
                -boldFont 1
                -sourceType "mel" 
                -longDivider 1
                menuEditorMenuItem24;

        setParent -m ..;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem8;

        menuItem
            -label "Create Description" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "XgCreateDescription" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "xgCreateDescription.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem1;

        menuItem
            -label "Guides Tool" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "XgGuideTool" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "xgGuideContext.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem2;

        menuItem
            -label "Sculpt Guides" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "python(\"xgui.createDescriptionEditor(False).guideSculptContext(False)\");\ntoolPropertyWindow -inMainWindow true;\nxgmGuideSculptContext -e -selHilight 1 xgmGuideSculptTool;\nxgmGuideSculptContext -e -volumetricSel 1 xgmGuideSculptTool" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "xgGuideSculptTool.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem3;

        menuItem
            -label "Primitives to Poly" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "python(\"import xgenm.xmaya.xgmConvertPrimToPolygon as cpp;cpp.convertPrimToPolygon(False)\")" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "xgPolyConvert.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem5;

        menuItem
            -label "menuEditorMenuItem8" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "python(\"import xgenm.xmaya.xgmConvertPrimToPolygon as cpp;cpp.convertPrimToPolygon(True)\")" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 1
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 0
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem10;

        menuItem
            -label "separator" 
            -divider 1
            -dividerLabel "separator" 
            -subMenu 0
            -tearOff 0
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem6;

        menuItem
            -label "XGen Library" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "XGenLibraryWindow" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "xgLibrary.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem12;

        menuItem
            -label "Export Meshes as Archive" 
            -divider 0
            -subMenu 0
            -tearOff 0
            -command "XgExportArchive;" 
            -altModifier 0
            -optionModifier 0
            -commandModifier 0
            -ctrlModifier 0
            -shiftModifier 0
            -optionBox 0
            -enable 1
            -data 0
            -allowOptionBoxes 1
            -postMenuCommandOnce 0
            -enableCommandRepeat 1
            -image "xgDEditor.png" 
            -echoCommand 0
            -italicized 0
            -boldFont 1
            -sourceType "mel" 
            -longDivider 1
            menuEditorMenuItem4;

    setParent -m ..;

setParent -m ..;

