
menuItem
-l "Alpha is Luminance On" 
-c "da_FileAlphaLuminance" 
-rp "E";

menuItem
-l "Alpha is Luminance Off" 
-c "da_FileNoAlphaLuminance" 
-rp "W";

menuItem
-l "Color Space sRGB" 
-c "da_FileColorSpaceSrgb" 
-rp "SE";

menuItem
-l "Color Space Raw" 
-c "da_FileColorSpaceRaw" 
-rp "SW";

menuItem
-l "Filter Type Off" 
-c "da_FileFilterOff" 
-rp "NW";

menuItem
-l "Filter Type Quadratic" 
-c "da_FileFilterQuadratic" 
-rp "NE";

setParent -m ..;

