
    menuItem
        -l "Extrude" 
        -d 0
        -sm 0
        -to 0
        -c "PolyExtrude" 
        -ob 0
        -en 1
        -rp "N" 
        -aob 1
        -pmo 0
        -i "polyExtrudeFacet.png" 
        menuEditorMenuItem1;

    menuItem
        -d 0
        -sm 0
        -to 0
        -c "PolyExtrudeOptions" 
        -ob 1
        -en 1
        -aob 1
        -pmo 0
        menuEditorMenuItem2;

setParent -m ..;

