
    menuItem
        -label "Set Fill Object" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "setLineModifierFillObject;" 
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "N" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -echoCommand 0
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem1;

setParent -m ..;

