
    menuItem
        -l "Connect selected Muscle Smart Collide nodes" 
        -d 0
        -sm 0
        -to 0
        -c "cMuscleSmartCollide_connectSCToSystem(1)" 
        -ob 0
        -en 1
        -data 0
        -rp "N" 
        -aob 1
        -pmo 0
        -ecr 1
        -i "cMuscle_smart_connect.png" 
        -ec 0
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem1;

setParent -m ..;

