
    menuItem
        -label "Add Mesh as Collider" 
        -command "AddCollider" 
        -radialPosition "N" 
        -image "expandContainer.png" 
        -sourceType "mel" 
        menuEditorMenuItem1;

    menuItem
        -label "Add Mesh as Deformer" 
        -command "AddDeformer" 
        -radialPosition "S" 
        -image "collapseContainer.png" 
        -sourceType "mel" 
        menuEditorMenuItem2;

setParent -m ..;

