
    menuItem
        -l "Wedge" 
        -c "WedgePolygon;" 
        -rp "N" 
        -i "polyWedgeFace.png" 
        menuEditorMenuItem1;

    menuItem
        -c "WedgePolygonOptions;" 
        -ob 1
        menuEditorMenuItem2;

    menuItem
        -l "Bevel" 
        -c "BevelPolygon;" 
        -rp "NW" 
        -i "polyBevel.png" 
        menuEditorMenuItem3;

    menuItem
        -c "BevelPolygonOptions;" 
        -ob 1
        menuEditorMenuItem4;

setParent -m ..;

