
    menuItem
        -l "Occupy Volume On" 
        -d 0
        -sm 0
        -to 0
        -c "da_ModifierOccupyVolume" 
        -ob 0
        -en 1
        -rp "E" 
        -aob 1
        -pmo 0
        menuEditorMenuItem1;

    menuItem
        -l "Occupy Volume Off" 
        -d 0
        -sm 0
        -to 0
        -c "da_ModifierNoOccupyVolume" 
        -ob 0
        -en 1
        -rp "W" 
        -aob 1
        -pmo 0
        menuEditorMenuItem2;

setParent -m ..;

