
    menuItem
        -label "Add Compass to Direction" 
        -divider 0
        -subMenu 0
        -tearOff 0
        -command "da_AirWindController" 
        -optionBox 0
        -enable 1
        -data 0
        -radialPosition "N" 
        -allowOptionBoxes 1
        -postMenuCommandOnce 0
        -enableCommandRepeat 1
        -image "out_implicitSphere.png" 
        -echoCommand 0
        -sourceType "mel" 
        -longDivider 1
        menuEditorMenuItem1;

setParent -m ..;

