
    menuItem
        -l "Convert to Interactive Groom" 
        -c "python(\"xgui.createXgIgConvertToInteractiveGroomWindow()\")" 
        -rp "E" 
        -i "xgConvertToIG.png" 
        menuEditorMenuItem1;

    menuItem
        -l "XGen Editor" 
        -c "if (!`pluginInfo -q -loaded xgenToolkit`) loadPlugin xgenToolkit.mll;XgCreateDescriptionEditor" 
        -i "xgDEditor.png" 
        menuEditorMenuItem2;

setParent -m ..;

